name: Release Flow

on:
  release:
    types: [prereleased, released]

jobs:
  publish-packages:
    name: Push Packages
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        os: [ubuntu-24.04]
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: addnab/docker-run-action@v3
        with:
          image: valory/open-autonomy-user:0.21.22
          options: -v ${{ github.workspace }}:/work
          run: |
            set -euo pipefail
            echo "Pushing Packages"
            cd /work
            autonomy init --reset --author valory --ipfs --remote
            autonomy push-all
